name: 'Deploy'
description: 'Deploy a Shopify application'
inputs:
  partners-token:
    required: true
  api-key:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install npm dependencies
      run: yarn install
      shell: bash
    - name: Deploy
      env:
        # Token from the Partner Dashboard
        SHOPIFY_CLI_PARTNERS_TOKEN: ${{ inputs.partners-token }}
        SHOPIFY_API_KEY: ${{ inputs.api-key }}
      run: yarn deploy
      shell: bash
